# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      PORT: ${{secrets.PORT}}
      DB_CNN: ${{secrets.DB_CNN}}
      SECRET_JWT_SEED: ${{secrets.SECRET_JWT_SEED}}
    
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: echo -e "PORT = ${{env.PORT}} \nDB_CNN= ${{env.DB_CNN}} \nSECRET_JWT_SEED= ${{env.SECRET_JWT_SEED}}" > .env
    - run: pm2 start /home/gitweb/actions-runner/data-backend/DataAnalytic/DataAnalytic/index.js --name 'DataAnalytic' --watch
